### ISSUE TITLE
Reformat does not work for non-Haskell files

### ISSUE THREAD

**Issue by xenog** [begriffs/haskell-vim-now#68] opened 2015-09-03 08:30 UTC
When editing a Markdown file, and attempting to use `gq` to reformat a paragraph, it attempts to use `stylish-haskell` to do so. Error messages are pasted into the buffer.

**Comment by begriffs** [comment] 2015-11-06 18:57
Hmm, I'm not able to reproduce. What type of file are you editing where `gq` does this? In the vimrc it tries to do stylish-haskell only for actual haskell files:

```viml
" Use par for prettier line formatting
set formatprg="PARINIT='rTbgqR B=.,?_A_a Q=_s>|' par\ -w72"

" Use stylish haskell instead of par for haskell buffers
autocmd FileType haskell let &formatprg="stylish-haskell"
```

**Comment by begriffs** [comment] 2016-05-25 06:22
Since there has been no reply to this issue I am closing it.

**Closed by begriffs** 2016-05-25 06:22 UTC
