### ISSUE TITLE
Using pointful on line returns incorrect haskell

### ISSUE THREAD

**Issue by ivanperez-keera** [begriffs/haskell-vim-now#108] opened 2015-11-27 02:59 UTC
I just added the following to a haskell file:
``` haskell
h x = f (filter ('a' ==) x)
```
When I use `,h.` it is correctly converted to:
``` haskell
h = f . filter ('a' ==)
```
When I use  `,h>` it becomes:
```haskell
h d = f (filter (\ a -> 'a' == a) d);
```
with an additional ; at the end, making it invalid haskell. From this point on, pointfree can no longer parse the line.

**Comment by begriffs** [comment] 2015-11-27 07:45
Thanks for reporting the bug. Do you think it's a problem with pointful itself or with the way haskell-vim-now interacts with it? Try opening an issue directly on https://github.com/23Skidoo/pointful

**Comment by begriffs** [comment] 2016-05-25 06:20
I can confirm the same issue on my machine. However I'm closing this issue because I think this is a problem with the pointful program.

**Closed by begriffs** 2016-05-25 06:20 UTC
