### ISSUE TITLE
error : ghcmod: ghc-mod is not executable!

### ISSUE THREAD

**Issue by varreli** [begriffs/haskell-vim-now#250] opened 2017-05-31 20:57 UTC
I get this error while loading a .hs file :
ghcmod: ghc-mod is not executable!
Press ENTER or type command to continue

 After hitting enter it is fine. This is on a 32bit Debian Jessie 8 system.

**Comment by varreli** [comment] 2017-05-31 23:17
From what I can tell, this is a problem with installing on a 32bit machine. I am having trouble with stack as well. It could be that stack and/or haskell-vim-now installed in the wrong directories. Though, I had it working for a while, editing in haskell-vim-now, saving and compiling / running from stack commands.

**Comment by begriffs** [comment] 2017-05-31 23:21
Can you paste the output of the installer (or create a [gist](https://gist.github.com/) and link to it if the output is huge)?

**Comment by varreli** [comment] 2017-06-01 00:07
you're talking about the output inside of vim or the output of the stack
installation?

**Comment by varreli** [comment] 2017-06-01 00:33
thanks!  here's the gist of both vim install and haskell-vim-now install.

https://gist.github.com/varreli/6ed319b53132e4dbab98f82e64801aac

**Comment by varreli** [comment] 2017-06-01 00:50
I'm running $ stack build primality now , and getting the same very slow process that I got for $ stack new primality:

https://gist.github.com/varreli/7e3e9b158a399087c0c31d236dde82ee

**Comment by varreli** [comment] 2017-06-01 01:01
just so you can see this in case it's wrong, here is the contents of ~/.stack/indices/Hackage :+1: 
~/.stack/indices/Hackage $ ls
01-index.tar7198853861649760492.gz  snapshot16816927771714636915.json
mirrors1957747793424238335.json     timestamp1804289383846930886.json
root.json

**Comment by begriffs** [comment] 2017-06-01 01:55
I see what's happening, the install script fails to install plugins using vim-plug, but doesn't notice that it failed. It dies early and fails to install the help programs like ghc-mod:

```
--- Installing plugins using vim-plug...
Error detected while processing function plug#end:
line   86:
E484: Can't open file /usr/share/vim/syntax/syntax.vim
```

I wonder if you have two installations of vim on your system. Perhaps you could try purging it and reinstalling:

```bash
sudo dpkg --purge --force-all vim
sudo apt-get update
sudo apt-get install vim
```

**Comment by varreli** [comment] 2017-06-01 02:31
thanks so much man. I just arrived in Colombia from Berkeley, CA. My host
in Colombia helped me sort out the stack issue ! so now I'll follow your
advice to see if I can get your package working. Gracias ! more drama later!
John

**Comment by varreli** [comment] 2017-06-01 03:04
hi I did as per your suggestion, then installed your package again. Now I have new errors:

~/haskell/primality/app $ vim Main.hs 
Error detected while processing function plug#end:
line   86:
E484: Can't open file /usr/share/vim/syntax/syntax.vim
Press ENTER or type command to continue

after ENTER I get the Main.hs file but the syntax highlighting is not on. It's plain white text.

**Comment by begriffs** [comment] 2017-06-01 03:11
Maybe the syntax file lives somewhere else and you can symlink it into place. Check

```bash
find /usr -name syntax.vim
```

**Comment by varreli** [comment] 2017-06-01 03:16
sorry there was no output. something's odd I had it working this morning except for that minor error message where I had to hit ENTER.

**Comment by varreli** [comment] 2017-06-01 03:17
ok sorry I found it with locate. one moment please.

**Comment by begriffs** [comment] 2017-06-01 03:59
I think if it's asking you to hit enter then it's not installing correctly. It should work automatically.

Where was the file when locate showed it to you? Perhaps you can link it to make vim happy, like

```bash
ln -s /path/to/syntax.vim /usr/share/vim/syntax/syntax.vim
```

Substituting the actual path where the file lives of course. The `ln` command may require sudo.

**Comment by varreli** [comment] 2017-06-01 04:22
this is how I created the symlink, I thought for certain it would work:
~ $ sudo ln -s .config/haskell-vim-now/.vim/bundle/vim-mundo/tests/bundled/lh-vim-lib/autoload/lh/syntax.vim /usr/share/vim/syntax/syntax.vim

However, I actually did a mkdir vim/syntax in /usr/share . The file syntax.vim is in /usr/share/vim/syntax/syntax.vim in red. so I'm assuming red indicates a live symlink.

**Comment by varreli** [comment] 2017-06-01 04:25
ie there was no vim directory at all in /usr/share, so I created one plus the syntax directory

**Comment by begriffs** [comment] 2017-06-01 04:45
I can confirm that something weird is going on. I think the install script on the master branch has been messed up and the problem was not caught by our continuous integration tests. On fresh servers of both Debian 8.8 32-bit and Ubuntu 16.04 64-bit as a sudoer user I run

```bash
sudo apt-get update
sudo apt-get install git gcc libc6-dev

curl -L https://git.io/haskell-vim-now > /tmp/haskell-vim-now.sh
bash /tmp/haskell-vim-now.sh
```

It seems to run OK and installs the plugins, but then the installer just stops and acts like it's done, with a success message. There is a lot more for it to do though! This may take some debugging. Perhaps #248 will have some effect once merged.

**Comment by varreli** [comment] 2017-06-01 04:57
At least I'm not mental. thanks so much - talk to you tomorrow.

**Comment by varreli** [comment] 2017-06-02 19:58
hi Joe, Just wanted to add that I found something odd about the install of
vim: in my home directory there was no .vim directory and no .vimrc file,
only what appeared to be symlinks.

I deleted the symlinks and just made a .vim directory and .vimrc file.

I wonder if that is normal.
John

**Comment by begriffs** [comment] 2017-06-06 18:19
I merged that PR -- try the installer again and see if it gets further.

**Comment by varreli** [comment] 2017-06-06 18:32
Cool thanks so much Joe! In the meantime I installed neoVim with a Haskell
package. Have no clue at this stage how to indent, etc. Vim is the weirdest
editor I've ever used. It's like pulling teeth so far !
Regards, John Werner

**Comment by begriffs** [comment] 2017-06-08 05:50
Yeah vim has a long history and has accumulated a lot of options. :smile:

Well if you ever want to give haskell-vim-now another try it does support NeoVim. But use whatever works best for you right now.

I'm closing this issue because I believe the PR fixed it.

**Closed by begriffs** 2017-06-08 05:50 UTC

**Comment by varreli** [comment] 2017-06-08 15:33
No it was my preferred choice from the beginning, after some reading. I
installed neovim temporarily just for survival and highlighting. I have no
opinion on vim -- can just use it for some basic haskell. I can't even get
indenting to work on neovim. I come from a very limited background: a
little ruby and scheme in DrRacket and played with some docker and vagrant
vm's.

I had a good day yesterday with learning haskell syntax. I'm trying to
transcribe the SICP problems to haskell (with help).

I'll install it today and give stack another shot. Please direct me to a
good tutorial if available. Thanks Joe best wishes.
