### ISSUE TITLE
How to install haskell-vim-now next to my current vim config

### ISSUE THREAD

**Issue by hnykda** [begriffs/haskell-vim-now#119] opened 2015-12-02 17:49 UTC
Hello,

I am aware that my old configuration of vim is saved in a backup folder. I really like `haskell-vim-now` and don't want to uninstall, but it basically made editing different files than `haskell` type hard. I am also using e.g. Python with specific plugins and settings, but hvn took over everything.

Is there a way how to quickly switch between these two configuration without copying everything, changing symlinks and so on? Is using `ftplugin` path the only solution? Couldn't then `haskell-vim-now` be installed to some folder (like `.config/haskell-vim-now`) and just provide file which should be copied to `ftplugin/haskell.vim`?

Thanks

**Comment by begriffs** [comment] 2015-12-02 18:12
You could try the vimrc.local trick to have your settings load along with the haskell stuff.

Docs: https://github.com/begriffs/haskell-vim-now#customizing

Let me know if that works.

**Comment by hnykda** [comment] 2015-12-03 07:49
I will take a look.

But to be honest, I really think that current approach is really not a good idea. Totally overriding multi-purpose editor for just one file type is just crazy. I've never experienced this in Linux world and I have been using it for ~5 years something. 

Don't get me wrong, I really like your work. Just a suggestion.

**Comment by begriffs** [comment] 2015-12-03 08:00
Agreed that it's heavy handed. I guess that's the philosophy of the project, to make an installer that fixes everything up for Haskell. If you have ideas to make it more modular I'd be happy to consider them.

**Comment by SimpleX91** [comment] 2015-12-03 09:11
HVN is an environment to develop in Haskell, which works as intended out-of-the-box with one-line installation. It's built around Haskell and *should* stay that way. IMO.
@hnykda if you want to configure your VIM for haskell, you should do that manually. HVN is *not* a framework. Yes, extensible, but that's all. There're some similar projects on github alone, not for vim only.
https://github.com/thoughtbot/dotfiles
https://github.com/skwp/dotfiles

If you want to make framework out of HVN, don't. But if you can and want to make a HVN plugin with all of it's features, that would be cool!

**Comment by hnykda** [comment] 2015-12-03 12:20
I believe I fully understand intentions behind this style - one-line installation is great. I don't know why do you think I think about HVN as a framework. On contrary, I am proposing an idea why it should be less "frameworky".  

But I can imagine that instead installing HVN over your current vim config, we could do something:

1. Copying `hvn` files as we do now
2. add an alias to your .bashrc/.zshrc like `hvim`, `haskell-vim-now`, `hvn`, `vimh` or whatever to something like `$HVN-DIR/activate.sh`
3. `activate.sh` would just set up different default `.vim` directory path as is described e.g. [here](http://superuser.com/questions/561434/telling-vim-to-use-custom-vimrc-is-easy-but-how-to-tell-it-to-use-alternative).

**Comment by begriffs** [comment] 2016-05-25 06:14
@hnykda thanks for the suggestion but I think it's out of scope. HVN is meant to be a preset kind of environment so that everyone gets the same experience. Totally understand that it's not right for everyone. However it's MIT licensed so feel free to use the HVN code as a basis for whatever you like.

**Closed by begriffs** 2016-05-25 06:14 UTC
